---
title: "Cleaning Seedling Exclosure Data"
author: "Camila Vargas"
date: "1/26/2022"
output: html_document
---
## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load packages
library(here)
library(tidyverse)
library(janitor)
library(readxl)
library(freeR)
library(lubridate)

## Sets R not to use scientific notations
options(scipen=999) 

```

## Exploring data
```{r}

excel_sheets(here::here("6.raw_data/SeedlingExclosures_Cooper.xlsx"))

```

2 sheets found. 
Data contains all necesary data
Key contains metadata info

## Read data
```{r}
seedling_raw <- read_excel(here::here("6.raw_data/SeedlingExclosures_Cooper.xlsx"), sheet = "Data") %>% 
  clean_names()
```

CHECK FOR WARNINGS! --> Numeric columns with n/a tun into character columns


## Inspection
```{r}
str(seedling_raw)

## class character but should be numeric. Chanfe n/a to NA
unique(seedling_raw$hx1)
unique(seedling_raw$dx1)
unique(seedling_raw$ux1)
unique(seedling_raw$lx1)

## class character, check if ok
unique(seedling_raw$crab_burrow)
unique(seedling_raw$herb_present)
unique(seedling_raw$notes)

## checking all character string in each column matches

unique(seedling_raw$tx)
unique(seedling_raw$sp)
unique(seedling_raw$damage_type) ## contains "n/a" need to change to actual NAs
```


## Cleaning data
```{r}
seed_clean <- seedling_raw %>%
  mutate(across(8:11, ~replace(., . == "n/a" , NA)),
         across(8:11, ~as.numeric(.)),
         damage_type = case_when(damage_type != "n/a" ~ damage_type),
         date = date(date))

## Checking
str(seed_clean)
range(seed_clean$date)
complete(seedling_raw)
complete(seed_clean)

## function to count n/a in raw data
count_na <- function(data){apply(data, 2, function(x) sum(x == "n/a", na.rm = T))}

count_na(seedling_raw)

## n/a have been successfully turned into NAs
## No NAs have been introduced in the process; NA values match

```

Next steps:
save data and create metadata doc!

## Save

```{r}

write_csv(seed_clean, here::here("7.clean_data/Palmyra_Cooper_Seedling_Exclosures_2004_2005.csv"))

```

